### ISSUE TITLE
设置 ZenHub：Sprint、OKRs、Release Milestone、Ideas

### ISSUE THREAD

**Issue by JimmyLv** [JimmyLv/JimmyLv#3]
## ACs

- [x] 有一些初始 ideas
- [x] 设置了 Roam 专栏发布计划
- [x] 将 ZenHub 设置 PWA，放入 Roam Research
- [x] ~~关闭第一个 Sprint 作为示例~~ Sprint 是时间维度自动变化的。
- [x] 能看到看板上的每一个列
- [x] 能看到有意义的报告

**Comment by JimmyLv** [comment]
目前的列包括：
- New Issues
- Icebox
- Sprint Backlog
- In Progress
- Review/QA
- Closed

![ZenHub-ZenHub - Board · JimmyLv's 2022-002832-20220530.png](https://images.zenhubusercontent.com/55c49f904f7a08fbb7f4225b/16872cbb-15cd-4b02-8f7f-bc1cc3335e3c)
